[package]
name = "mail-core"
version.workspace = true
edition.workspace = true

[dependencies]
async-imap = { version = "0.11.3", default-features = false, features = ["runtime-tokio"] }
chrono = { version = "0.4.45", features = ["serde"] }
directories = "6.0.0"
futures = "0.3.34"
keyring = "4.2.0"
lettre = { version = "0.11.23", default-features = false, features = ["tokio1-rustls-tls", "builder", "smtp-transport"] }
mail-parser = "0.11.8"
mime_guess = "2.0.5"
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustls = "0.23.43"
rustls-native-certs = "0.8.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "time", "sync", "io-util", "fs"] }
tokio-rustls = "0.26.5"
toml = "1.1.5"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
